/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.DrawablesDao;
import Drawable.Drawable;
import java.awt.Graphics;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;

import models.Shape;  // Importa el modelo de figura
import models.Circle;  // Importa el modelo de círculo
import models.Rectangle;  // Importa el modelo de rectángulo
import models.Square;
import models.Elipse;

/**
 *
 * @author ESTUDIANTE
 */
public class MainPanel extends javax.swing.JPanel {
    private final DrawablesDao drawables;
    private final JLabel areaLabel;
    /**
     * Creates new form MainPanel
     * @param dao
     */
    public MainPanel(DrawablesDao dao) {
        initComponents();
        this.setSize(1366,726);
        this.drawables=dao;
        this.setLayout(null);
        this.areaLabel = new JLabel("Area total: 0%zxvzxcvzxcvzxcvxzcv");
        this.areaLabel.setFont(new Font("Arial", Font.PLAIN, 18));
        this.areaLabel.setForeground(Color.BLACK);
        this.add(areaLabel);  // Agregar el JLabel al panel
        this.areaLabel.setBounds(20, 20, 300, 30);
    }
    
    public void updateAreaLabel(String text) {
        areaLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
        protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Itera sobre las figuras y las dibuja
        for (Drawable d : drawables.getDrawables()) {
            if (d instanceof Shape shape) {
                shape.draw(g);
            }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
